env: local  #local, prod
http_server:
    address: "localhost:8081"
    timeout: 4s
    idle_timeout: 60s
postgres_db:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "whitemazin2011"
    dbname: "mizar_db"
    sslmode: "disable"
